CREATE TABLE address(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(500) NOT NULL,
	email VARCHAR(500) NOT NULL,
	phone INTEGER NOT NULL,
	address VARCHAR(500) NOT NULL,
	pin INTEGER NOT NULL,
	relation VARCHAR(500) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE address
ADD COLUMN user_id INTEGER,
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id) REFERENCES users(id);
