CREATE TABLE users(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(500) NOT NULL,
	email VARCHAR(500) UNIQUE NOT NULL,
	password VARCHAR(500) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);